"use client";
import Head from "next/head";
import PaymentGateway from "./PaymentGateWay/PaymentGateWay";

export default function Home() {
  function handleClick() {
    PaymentGateway();
  }

  return (
    <div className="bg-white items-center">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src="https://www.payhere.lk/lib/payhere.js"
          async
        ></script>
      </Head> */}
      <div className=" text-black">Pay here</div>
      <button className="bg-red-400" onClick={handleClick}>
        Start Payment
      </button>
    </div>
  );
}
